### ISSUE TITLE
Hi,error when running the quick start commend

### ISSUE THREAD

**Issue by javafish** [tyMadara/ILS-CSL#1]
Hi, I got below error when running the quick start commend:

**Comment by javafish** [comment]
❌ Wrong LLM answers in the history: 5 / 17 / 44
📝 Write json file to out/gpt_history/gpt-4/asia_wrong.json.
Traceback (most recent call last):
  File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 542, in <module>
    icsl.iter_causal_structure_learning()
  File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 247, in iter_causal_structure_learning
    write_json(self.prior_iter, self.prior_iter_path)
  File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/utils.py", line 567, in write_json
    with open(json_path, "w", encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/prior-iter/asia-250-1-CaMML-mml.json'

Can you please help?

**Comment by tyMadara** [comment]
you may make a dir out/prior-iter/ and try again

**Comment by javafish** [comment]
hi, i did try again and got this error: can you pls help?

📖 Read txt file from prompt/start.txt.
📖 Read txt file from prompt/background.txt.
📖 Read txt file from prompt/question.txt.
📖 Read json file from prompt/domain.json.
📖 Read json file from prompt/description/asia.json.
🔁 Iteration:  1
Existing edges: []
Forbidden edges: []
Metrics: {'extra': 0, 'missing': 1, 'reverse': 2, 'fdr': 0.2857, 'tpr': 0.625, 'fpr': 0.1, 'shd': 3, 'nnz': 7, 'precision': 0.7143, 'recall': 0.625, 'F1': 0.6667, 'gscore': 0.375, 'iter_num': 1, 'time': 
1.3387, 'exist_mode': 'edge'}
Candidate edges: 7
📖 Read json file from out/gpt_history/gpt-4/asia_history.json.
🔍 Already queried: tuberculosis->either_turb_or_lung_cancer (Ans: A / A)
🔍 Already queried: lung_cancer->smoking (Ans: B / B)
🔍 Already queried: lung_cancer->either_turb_or_lung_cancer (Ans: A / A)
🔍 Already queried: bronchitis->smoking (Ans: B / B)
🔍 Already queried: bronchitis->dyspnoea (Ans: A / A)
🔍 Already queried: either_turb_or_lung_cancer->positive_xray (Ans: A / A)
🔍 Already queried: either_turb_or_lung_cancer->dyspnoea (Ans: A / A)
📝 Write json file to out/summary/gpt-4/asia_summary.json.
Traceback (most recent call last):
  File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 542, in <module>
    icsl.iter_causal_structure_learning()
  File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 234, in iter_causal_structure_learning
    self.result_data = self.result_data.append(
  File "/home/jia/miniconda3/envs/edu2/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by tyMadara** [comment]
you may check if the proper version of pandas is correctly installed

**Comment by buhuiCS** [comment]
> ❌ Wrong LLM answers in the history: 5 / 17 / 44 📝 Write json file to out/gpt_history/gpt-4/asia_wrong.json. Traceback (most recent call last): File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 542, in icsl.iter_causal_structure_learning() File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/main.py", line 247, in iter_causal_structure_learning write_json(self.prior_iter, self.prior_iter_path) File "/home/jia/下载/IJCAI 2024/Casual Structure learning/ILS-CSL-main/utils.py", line 567, in write_json with open(json_path, "w", encoding=encoding) as f: FileNotFoundError: [Errno 2] No such file or directory: 'out/prior-iter/asia-250-1-CaMML-mml.json'
> 
> Can you please help?

hi,did you solve this question
